export const TypesActions = {
    FETCH_FOR_MOVIES: "FETCH_FOR_MOVIES",
     SEARCH_MOVIE: "SEARCH_MOVIE",
    SELECT_MOVIE: "SELECT_MOVIE",
    LIKE_MOVIE: "LIKE_MOVIE",
    ADD_TO_MY_LIST_MOVIE: "ADD_TO_MY_LIST_MOVIE",
    REMOVE_FROM_MY_LIST: "REMOVE_FROM_MY_LIST",
    GET_MOVIES: "GET_MOVIES",
}